### ISSUE TITLE
"hledger":executable file not found in $PATH when syncing on Mac

### ISSUE THREAD

**Issue by gitting** [ananthakumaran/paisa#67] opened 2023-10-04 03:11 UTC
**Describe your Environment**
OS: Mac Sonoma intel
Paisa Version: 0.5.3
App Variant: Desktop
Locale: en-US

**Describe the bug**
Opening paisa via spotlight fails to sync for a `hledger` configuration.

**To Reproduce**

- ensure `hledger` is installed and works against the hledger journal
- verify `echo $PATH | grep -i ledger` shows no output, that is, `hledger` is not in the path
- ensure `which hledger` finds it
- install desktop paisa on mac according to installation instructions
- launch it for the first time according to Mac requirements per instructions to clear the security
- now quit it
- now open it via Spotlight
- modify configuration (this can be done manually in `~/Documents/paisa/paisa.yaml`)
  - point to your hledger journal
  - set `ledger_cli` to `hledger`
- click `Sync Journal` in upper righthand corner dropdown menu
- observe error dialog box describing failure `exec: "hledger":executable file not found in $PATH`

**Expected behavior**
`Sync` succeeds since `hledger` can be reached via `which`.

**Comment by ananthakumaran** [comment] 2023-10-04 03:34
@gitting this issue and the @@ issue are fixed on master. I am not able to reproduce the UTF-8 error you were getting. Could you open an issue for that with a sample transaction? I tried to add utf-8 chars `;; ß ä ö ü Ä Ö Ü` and tested it on my mac, and it seems to work. The error itself comes from hledger, but this is likely because the LC_* env variables are not set correctly when started outside of terminal.

**Comment by gitting** [comment] 2023-10-04 04:08
Done. See https://github.com/ananthakumaran/paisa/issues/68

**Comment by ananthakumaran** [comment] 2023-10-07 07:36
fixed on v0.5.4

**Closed by ananthakumaran** 2023-10-07 07:36 UTC
