### ISSUE TITLE
Toggling mode causes data reload

### ISSUE THREAD

**Issue by ginruh** [ananthakumaran/paisa#37] opened 2023-09-24 19:16 UTC
**Describe your Environment**
OS: Windows 11
Paisa Version: 0.5.1
App Variant: Desktop

**Describe the bug**
Changing dark mode to light mode or vice versa reloads data

**Expected behavior**
Mode should change but data shouldn't be reloaded IMHO.

**Comment by ananthakumaran** [comment] 2023-09-25 01:20
Have you tried the latest master? I have put a fix for this issue, also reported by https://github.com/ananthakumaran/paisa/issues/26

I know reloading the page is not ideal and I indeed started with CSS change only. There are a few places where I set the color from javascript (SVGs) and just changing at the CSS level would leave them in an ugly state, so I decided to make this tradeoff (vs handling it all over the code). But you shouldn't lose any data because of this. Let me know if there are any cases where you can lose data due to this.

**Comment by ginruh** [comment] 2023-09-25 07:18
I have tested this on [demo](https://demo.paisa.fyi). I am guessing that it will be latest.

**Comment by ananthakumaran** [comment] 2023-09-25 13:00
Just to clarify, the page does reload when you toggle the switch. This is known, but on the editor page, if you have unsaved changes, then you should get a popup asking for confirmation. Let me know if you don't get that popup. Please record and post a GIF if that's the case. I have tested it and not able to reproduce the issue

**Comment by ginruh** [comment] 2023-09-26 19:21
There are some issues I found on the editor page:-

- Clicking on cancel button in the confirmation box changes the mode but doesn't reload
  If one clicks cancel then one expects that no changes will take place but theme color changes but the editor doesn't reload. IMHO it is inconsistent.
- I think confirmation popup is a wrong idea
  Many browsers disable by default or give the option to disable popup if they show frequently. I think you should have a custom dialog component.
  
In the end I am adding a small video about the above things I mentioned.

https://github.com/ananthakumaran/paisa/assets/26306108/6756e81c-a07e-4647-a418-c873332a8466

**Closed** 2023-09-30 05:03 UTC
