### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by maacl** [ananthakumaran/paisa#181] opened 2024-02-13 23:29 UTC
**Describe your Environment**
OS: Windows 11
Paisa Version: 0.6.6 (2024-02-10)
App Variant: Desktop

**Describe the bug**
App crashes upon start.

**To Reproduce**
1. Start app.

**Expected behavior**
App starts.

**Screenshots**
![image](https://github.com/ananthakumaran/paisa/assets/64092/b9395633-1cc1-4457-84c3-e0b7a8802636)

**Journal**
N/A

**Comment by ananthakumaran** [comment] 2024-02-14 01:57
Paisa is not able to create the `paisa` folder under `Documents` folder. I am not sure about the reason, do you have ransomware protection enabled? check https://github.com/ananthakumaran/paisa/issues/115

**Comment by maacl** [comment] 2024-02-14 05:42
I have, and I can't very well switch it off. On Windows all apps store
critical data in the app data folder.

**Comment by ananthakumaran** [comment] 2024-02-14 13:14
duplicate of #115, we will continue the discussion there.

**Closed** 2024-02-14 13:14 UTC
