### ISSUE TITLE
SQL : uint64 values with high bit set are not supported 

### ISSUE THREAD

**Issue by mankoff** [ananthakumaran/paisa#173] opened 2024-02-10 18:37 UTC
**Describe your Environment**
OS: Linux Kubuntu 22.04
Paisa Version: 0.6.2
App Variant: CLI

**Describe the bug**
This  is the same bug as reported on #146 but it's not Mac-specific per that title. I'm seeing it on Linux too.

Here are the lines that cause it:

```
2024-01-14 pad Assets:Other:DeltaECredits  Equity:OpeningBalances

2024-01-15 balance Assets:Other:DeltaECredits 802.80 USD
```

And the output of `PAISA_DEBUG=true ./paisa update` is

```
ERROR   [logger.go:53] Trace INSERT INTO `postings` (`transaction_id`,`date`,`payee`,`account`,`commodity`,`quantity`,`amount`,`status`,`tag_recurring`,`tag_period`,`transaction_begin_line`,`transaction_end_line`,`file_name`,`forecast`,`note`,`transaction_note`) VALUES ("a520471362796bf9f2d4eef7c48622ae","2024-01-14 00:00:00","(Padding inserted for Balance of 802.80 USD for difference 497.00 USD)","Assets:Other:DeltaECredits","USD","497","497","unmarked","","",18446744073709551615,1,"bc.org",false,"","") RETURNING `id` [31.219µs]  error="sql: converting argument $11 type: uint64 values with high bit set are not supported"
FATAL   [posting.go:123] UpsertAll sql: converting argument $11 type: uint64 values with high bit set are not supported 
```

**Comment by ananthakumaran** [comment] 2024-02-11 03:38
Thanks for the info, the issue is due to the pad directive which returns incorrect line numbers. I have pushed a fix to master

**Closed by ananthakumaran** 2024-02-11 03:38 UTC

**Comment by mankoff** [comment] 2024-02-15 04:18
Thanks. Are there docs how to build or run from source until a new release is issued?

**Comment by ananthakumaran** [comment] 2024-02-15 04:19
checkout [Dockerfile](https://github.com/ananthakumaran/paisa/blob/master/Dockerfile)
